kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "bluegreen-pipeline"
spec:
  source:
    git:
      uri: "http://github.com/wkulhanek/openshift-bluegreen"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
  env:
  - name: COLOR
    value: yellow
